### Set avatar
# To set avatar, run both frontend and backend, and upload through the website
# http does not do a good job handling PATCH'ing multipart/form-data

### Get avatar
GET http://localhost:8080/api/profile-picture/bd548303-62b7-4535-9bc1-f6a7f30aee19