/*
 * General notes:
 * - All timestamps are stored as UTC and converted to the user's local timezone
 */
drop table if exists public.registrations;
drop table if exists public.event_sponsors;
drop table if exists public.event_roles;
drop table if exists public.events;
drop table if exists public.users;

/*
 *
 * Table of registered users.
 *
 * Notes:
 * - Raw password strings are hashed by the server during authentication
 * - is_deleted flag removes the need to update the events table if an account is deleted
 */
create table public.users (
  user_id uuid not null default gen_random_uuid(),
  email character varying not null,
  password_hash character varying not null,
  username character varying not null,
  avatar_url character varying null,
  updated_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  is_deleted boolean not null default false,
  primary key (user_id),
  unique (email),
  unique (username)
) tablespace pg_default;

/*
 * Table of race events.
 *
 * Notes:
 * - Race details (longitutde, distance, etc.) stored here assumes there is only
 *   one race per event
 * - This table will only cascade from updates to user_id; see is_deleted flag note
 */
create table public.events (
  event_id bigint generated by default as identity not null,
  creator_user_id uuid not null,
  name character varying not null,
  description text null,
  event_datetime timestamp with time zone null,
  latitude double precision null,
  longitude double precision null,
  distance real null,
  elevation real null,
  difficulty character varying null,
  updated_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  primary key (event_id),
  foreign KEY (creator_user_id) references users (user_id)
    on update CASCADE
) tablespace pg_default;

/*
 * Table of each role type and limit for race events.
 *
 * Notes:
 * - This is excessive for the project, but is good design for scalability
 * - Composite key prevents duplicate roles for any given event
 */
create table public.event_roles (
  event_id bigint not null,
  role character varying not null,
  role_limit smallint not null,
  primary key (event_id, role),
  foreign key (event_id) references events (event_id) 
    on update CASCADE
    on delete CASCADE,
  constraint positive_role_limit check (role_limit > 0)
) tablespace pg_default;

/*
 * Table of sponsors and prizes for race events.
 *
 * Notes:
 * - Composite key ensures sponsors cannot lot duplicate prizes for each event;
 *   multiples of the same prize is handled by the quantity field
 */
create table public.event_sponsors (
    id bigint generated always as identity,
    event_id bigint not null,
    sponsor character varying not null,
    prize character varying null,
    primary key (id),
    foreign key (event_id) references events (event_id)
        on update CASCADE
        on delete CASCADE
) tablespace pg_default;

/*
 * Table of users registered to events.
 * 
 * Notes:
 * - start_time/finish_time stored here assumes each event has one race
 * - role stored here assumes each user can only have one role per event
 * - composite key enforces that each user can only register for each event once
 * - elapsed_time is stored to prevent errors during repeat calculations
 */
create table public.registrations (
  event_id int8 not null,
  user_id uuid not null,
  role varchar(50) not null,
  start_time timestamptz,
  finish_time timestamptz,
  elapsed_time interval generated always as (finish_time - start_time) stored,
  created_at timestamptz not null default now(),
  primary key (event_id, user_id),
  foreign key (event_id) references events (event_id),
  foreign key (user_id) references users (user_id),
  foreign key (event_id, role) references event_roles(event_id, role)
    on update CASCADE
    on delete RESTRICT
) tablespace pg_default;
